feat: IG android - open share screen
react-native-share/react-native-share pull request #1085
Opened 2021-09-07 14:25 UTC by ddereszewski

# Overview
This introduces a new feature to IG single share. 
I found out how to open share views on IG without providing media.  

# Test Plan
As added in docs

2021-09-07 14:51 UTC, mikehardy requested changes
Interesting - thanks for posting this!

Seems good but spacing doesn't match project and I worry about just eating that exception... what do you think of my suggestions?

2021-09-07 14:51 UTC, mikehardy commented on android/src/main/java/cl/json/social/InstagramShare.java
> +        }catch (Exception e){
Best to match existing spacing style

```suggestion
        } catch (Exception e) {
```

2021-09-07 14:51 UTC, mikehardy commented on android/src/main/java/cl/json/social/InstagramShare.java
> +            // bad param passed
If these are simply consumed with no output whatsover, when the params required inevitably change upstream there will be no notice for anyone anywhere. So these should be logged somehow. The question is severity. For severity "error" means execution should halt as state is undefined - that is not correct here, "info" means no problem really just something you should know - that is also not quite right, "warning" means something unexpected and bad but we think we can continue. I think that fits.

```suggestion
            // bad param passed
            android.util.Log.warn("RNShare", e.getMessage());
```

2021-09-09 07:05 UTC, ddereszewski commented
pushed the fixed. 

I decided to allow `instagram://*` patter for Android as it works but it's nowhere documented. Folks might use it in some other way to achieve some other results. 

Also, I didn't want to introduce any other new param,  increase complexity and make params less generic (Story case). Therefore I suggest a solution to use URL

2021-09-10 01:30 UTC, MateusAndrade approved these changes
Nice! Thanks a lot @ddereszewski! 🚀

2021-09-10 01:32 UTC, MateusAndrade commented
Do you think we can follow with this @mikehardy? 🤔

2021-09-10 01:34 UTC, mikehardy approved these changes
Sure seems fine by me - were suggestions were more sort of general and not related to the feature, I'll defer to anyone (which is certainly @ddereszewski here...) that's actually working on and testing it. I have no idea how Instagram works at an integration / API level haha

2021-09-10 01:34 UTC, merged

2021-09-10 01:36 UTC, MateusAndrade commented
:tada: This PR is included in version 7.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-share/v/7.1.0)
- [GitHub release](https://github.com/react-native-share/react-native-share/releases/tag/v7.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: