accepting ph asset uri as background video
react-native-share/react-native-share pull request #947
Opened 2021-01-12 00:46 UTC by Gokaysim

# Overview

# Test Plan

2021-03-03 19:47 UTC, Gokaysim reviewed
minor bug fix

2021-03-04 05:03 UTC, MateusAndrade requested changes

2021-03-04 05:03 UTC, MateusAndrade commented on ios/InstagramStories.m
> +                    return;
```suggestion
                      RCTLogError(@"Cannot load a photo library asset with no URL");
                      return;
```

2021-03-04 05:03 UTC, MateusAndrade commented on ios/InstagramStories.m
> +                    results = [PHAsset fetchAssetsWithALAssetURLs:@[imageURL] options:nil];
```suggestion
                      assetID = [imageURL absoluteString];
                      results = [PHAsset fetchAssetsWithALAssetURLs:@[imageURL] options:nil];
```

2021-03-04 05:03 UTC, MateusAndrade commented on ios/InstagramStories.m
> +                    results = [PHAsset fetchAssetsWithLocalIdentifiers:@[assetID] options:nil];
```suggestion
                      assetID = [imageURL.absoluteString substringFromIndex:@"ph://".length];
                      results = [PHAsset fetchAssetsWithLocalIdentifiers:@[assetID] options:nil];
```

2021-03-04 05:03 UTC, MateusAndrade commented on ios/InstagramStories.m
> +                    return;
```suggestion
                      return;
```

2021-03-04 05:03 UTC, MateusAndrade commented on ios/InstagramStories.m
> +                }
```suggestion
                } else {
                     NSData *backgroundVideo = [[NSFileManager defaultManager] contentsAtPath: URL];
                     [self backgroundVideo: backgroundVideo];
                }
```

2021-03-04 05:03 UTC, MateusAndrade commented on ios/InstagramStories.m
> +                else if([URL hasPrefix:@"http"]){
```suggestion
                }  else if([URL hasPrefix:@"http"]) {
```

2021-03-04 05:05 UTC, MateusAndrade commented
Hey @Gokaysim thanks for your help, would mind filling in what these changes address or what is the purpose? Also, how we would end using this? 

I saw that we are using the ` Photo`  SDK from iOS, we use this to access the local file and pass it directly to `Instagram`?

2021-03-07 12:35 UTC, Gokaysim commented
if the backgroundvideo URI is given as PHAsset it fetches the file with it. If the file is given as http url it downloads it in a different thread.

2021-05-27 02:10 UTC, closed without merging

2021-07-20 13:49 UTC, vforvasile commented
@MateusAndrade  how come this isn't merged?